//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertConfig) DeepCopyInto(out *AlertConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertConfig.
func (in *AlertConfig) DeepCopy() *AlertConfig {
	if in == nil {
		return nil
	}
	out := new(AlertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metrics) DeepCopyInto(out *Metrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metrics.
func (in *Metrics) DeepCopy() *Metrics {
	if in == nil {
		return nil
	}
	out := new(Metrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutGuard) DeepCopyInto(out *RolloutGuard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutGuard.
func (in *RolloutGuard) DeepCopy() *RolloutGuard {
	if in == nil {
		return nil
	}
	out := new(RolloutGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RolloutGuard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutGuardList) DeepCopyInto(out *RolloutGuardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RolloutGuard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutGuardList.
func (in *RolloutGuardList) DeepCopy() *RolloutGuardList {
	if in == nil {
		return nil
	}
	out := new(RolloutGuardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RolloutGuardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutGuardSpec) DeepCopyInto(out *RolloutGuardSpec) {
	*out = *in
	out.Metrics = in.Metrics
	in.Thresholds.DeepCopyInto(&out.Thresholds)
	out.AlertConfig = in.AlertConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutGuardSpec.
func (in *RolloutGuardSpec) DeepCopy() *RolloutGuardSpec {
	if in == nil {
		return nil
	}
	out := new(RolloutGuardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutGuardStatus) DeepCopyInto(out *RolloutGuardStatus) {
	*out = *in
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.ObservedLatency != nil {
		in, out := &in.ObservedLatency, &out.ObservedLatency
		*out = new(float64)
		**out = **in
	}
	if in.ObservedErrorRate != nil {
		in, out := &in.ObservedErrorRate, &out.ObservedErrorRate
		*out = new(float64)
		**out = **in
	}
	if in.RolloutStartTime != nil {
		in, out := &in.RolloutStartTime, &out.RolloutStartTime
		*out = (*in).DeepCopy()
	}
	if in.MonitoringEndTime != nil {
		in, out := &in.MonitoringEndTime, &out.MonitoringEndTime
		*out = (*in).DeepCopy()
	}
	if in.FirstViolationTime != nil {
		in, out := &in.FirstViolationTime, &out.FirstViolationTime
		*out = (*in).DeepCopy()
	}
	if in.LastHealthyRevision != nil {
		in, out := &in.LastHealthyRevision, &out.LastHealthyRevision
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutGuardStatus.
func (in *RolloutGuardStatus) DeepCopy() *RolloutGuardStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutGuardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Thresholds) DeepCopyInto(out *Thresholds) {
	*out = *in
	if in.GracePeriodSeconds != nil {
		in, out := &in.GracePeriodSeconds, &out.GracePeriodSeconds
		*out = new(int32)
		**out = **in
	}
	if in.EvaluationWindowSeconds != nil {
		in, out := &in.EvaluationWindowSeconds, &out.EvaluationWindowSeconds
		*out = new(int32)
		**out = **in
	}
	if in.ConsecutiveFailures != nil {
		in, out := &in.ConsecutiveFailures, &out.ConsecutiveFailures
		*out = new(int32)
		**out = **in
	}
	if in.MonitoringWindowSeconds != nil {
		in, out := &in.MonitoringWindowSeconds, &out.MonitoringWindowSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Thresholds.
func (in *Thresholds) DeepCopy() *Thresholds {
	if in == nil {
		return nil
	}
	out := new(Thresholds)
	in.DeepCopyInto(out)
	return out
}
